---
# tasks file for logging-aws
- name: Update package cache
  yum:
    name: '*'
    state: latest
  become: true

- name: Install Python and pip
  yum:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - python3
    - python3-pip

- name: Install boto3
  pip:
    name: boto3
    executable: pip3.7
    state: present

- name: Gather facts
  ec2_metadata_facts:
  register: ec2_metadata

- name: Ensure .aws directory exists
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    mode: '0700'

- name: Create AWS credentials file
  template:
    src: aws_credentials.j2
    dest: ~/.aws/credentials
    mode: '0600'

- name: Create AWS config file
  template:
    src: aws_config.j2
    dest: ~/.aws/config
    mode: '0600'

- name: Attach IAM role
  command: >
          aws ec2 associate-iam-instance-profile
          --instance-id {{ instance_id }}
          --iam-instance-profile Name={{ iam_instance_profile_name }}
  register: attach_iam_result
  when: ec2_metadata.ansible_facts.ansible_ec2_iam_info is not defined

- name: Install AWSLogs agent
  yum:
    name: awslogs
    state: present

- name: Delete default log group
  amazon.aws.cloudwatchlogs_log_group:
    state: absent
    log_group_name: /var/log/messages

- name: Recursively remove directory
  ansible.builtin.file:
    path: ~/.aws
    state: absent

- name: Deploy awslogs conf on server
  template:
    src: awslogs.j2
    dest: /etc/awslogs/awslogs.conf
    backup: yes
  when: ansible_distribution == "Amazon"
  notify: Restart service awslogsd

